/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActorTimelineDialog: typeof import('./src/components/dialogs/ActorTimelineDialog.vue')['default']
    AnomaliesChart: typeof import('./src/components/charts/AnomaliesChart.vue')['default']
    CountryActorsDialog: typeof import('./src/components/dialogs/CountryActorsDialog.vue')['default']
    DeployWizard: typeof import('./src/components/DeployWizard.vue')['default']
    DeviceDetailsDialog: typeof import('./src/components/dialogs/DeviceDetailsDialog.vue')['default']
    GeographicConnectionsChart: typeof import('./src/components/charts/GeographicConnectionsChart.vue')['default']
    IndustrialProtocolChart: typeof import('./src/components/charts/IndustrialProtocolChart.vue')['default']
    ProtocolDistributionChart: typeof import('./src/components/charts/ProtocolDistributionChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopIPsChart: typeof import('./src/components/charts/TopIPsChart.vue')['default']
    TrafficOverTimeChart: typeof import('./src/components/charts/TrafficOverTimeChart.vue')['default']
  }
}
